"""add ai call limit

Revision ID: 695452f6d992
Revises: 0299b714f778
Create Date: 2026-05-20 16:35:27.395102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695452f6d992'
down_revision = '0299b714f778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_ai_calls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_ai_call_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('last_ai_call_date')
        batch_op.drop_column('daily_ai_calls')

    # ### end Alembic commands ###
