"""empty message

Revision ID: ca1256624a79
Revises: 0763d677d453
Create Date: 2026-05-06 02:29:46.017188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1256624a79'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('calories', sa.String(length=120), nullable=False),
    sa.Column('protein', sa.String(length=120), nullable=False),
    sa.Column('carbs', sa.String(length=120), nullable=False),
    sa.Column('fat', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calories'),
    sa.UniqueConstraint('carbs'),
    sa.UniqueConstraint('fat'),
    sa.UniqueConstraint('protein')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrition')
    op.drop_table('meal')
    # ### end Alembic commands ###
